import type {
  ConversationOutputProjection,
  ConversationSourceProjection,
} from "@rah/runtime-protocol";
import { useMemo, useState } from "react";
import {
  ChevronDown,
  ChevronRight,
  Globe2,
  Image as ImageIcon,
  Search,
} from "lucide-react";
import { FileResourceIcon } from "../components/chat/FileResourceIcon";
import { getDisplayPath } from "./shared";

type InspectorResource = ConversationOutputProjection | ConversationSourceProjection;

function isSourceResource(
  resource: InspectorResource,
): resource is ConversationSourceProjection {
  return "activities" in resource;
}

export function groupInspectorSourceResources(
  resources: readonly ConversationSourceProjection[],
): {
  primary: ConversationSourceProjection[];
  searchResults: ConversationSourceProjection[];
} {
  const primary: ConversationSourceProjection[] = [];
  const searchResults: ConversationSourceProjection[] = [];
  for (const resource of resources) {
    if (
      resource.url &&
      resource.activities.includes("searched") &&
      !resource.activities.includes("fetched")
    ) {
      searchResults.push(resource);
    } else {
      primary.push(resource);
    }
  }
  return { primary, searchResults };
}

export function inspectorResourceLabel(resource: InspectorResource): string {
  if (!resource.url) return resource.label;
  try {
    const url = new URL(resource.url);
    const segments = url.pathname
      .split("/")
      .filter(Boolean)
      .map((segment) => decodeURIComponent(segment));
    if (segments.length === 0) return resource.label;
    let leaf = segments.at(-1)!.replace(/\.(?:html?|php)$/i, "");
    if (/^(?:index|reference)$/i.test(leaf) && segments.length > 1) {
      const parent = segments.at(-2)!.replace(/\.(?:html?|php)$/i, "");
      leaf = `${parent}/${leaf}`;
    }
    return leaf || resource.label;
  } catch {
    return resource.label;
  }
}

function detail(resource: InspectorResource, workspaceRoot: string): string {
  if (resource.path) return getDisplayPath(resource.path, workspaceRoot);
  if (resource.url) return resource.url;
  return "activity" in resource ? resource.activity : resource.activities.join(" · ");
}

function relationLabel(resource: InspectorResource): string {
  if ("activity" in resource) {
    switch (resource.activity) {
      case "written":
        return "Written during the task";
      case "updated":
        return "Updated during the task";
      case "generated":
      default:
        return "Generated by the conversation";
    }
  }
  const labels = resource.activities.map((activity) => {
    switch (activity) {
      case "provided":
        return "Attached to the conversation";
      case "read":
        return "Read during the task";
      case "searched":
        return "Found during web search";
      case "fetched":
        return "Opened during the task";
    }
  });
  return labels.join(" · ");
}

function ResourceIcon(props: { resource: InspectorResource }) {
  if (props.resource.path) {
    return (
      <FileResourceIcon
        path={props.resource.path}
        size={15}
        className="shrink-0 text-[var(--app-hint)]"
      />
    );
  }
  return props.resource.kind === "image" ? (
    <ImageIcon size={15} className="shrink-0 text-[var(--app-hint)]" />
  ) : (
    <Globe2 size={15} className="shrink-0 text-[var(--app-hint)]" />
  );
}

function ResourceRow(props: {
  resource: InspectorResource;
  workspaceRoot: string;
  nested?: boolean;
  onOpenFile: (path: string) => void;
  onOpenUrl: (url: string) => void;
}) {
  const content = (
    <>
      <ResourceIcon resource={props.resource} />
      <div className="min-w-0 flex-1">
        <div className="truncate text-[13px] font-medium text-[var(--app-fg)]">
          {inspectorResourceLabel(props.resource)}
        </div>
        <div className="truncate text-[11px] text-[var(--app-hint)]">
          {detail(props.resource, props.workspaceRoot)}
        </div>
        <div className="truncate text-[11px] text-[var(--app-hint)]">
          {relationLabel(props.resource)}
        </div>
      </div>
    </>
  );
  const className = `flex min-h-[44px] w-full items-center gap-1.5 rounded-md py-1 text-left ${
    props.nested ? "pl-5 pr-1.5" : "px-1.5"
  }`;
  if (!props.resource.path && !props.resource.url) {
    return <div className={className}>{content}</div>;
  }
  return (
    <button
      type="button"
      className={`${className} transition-colors hover:bg-[var(--app-bg)]`}
      title={props.resource.path ?? props.resource.url ?? props.resource.label}
      onClick={() => {
        if (props.resource.path) props.onOpenFile(props.resource.path);
        else if (props.resource.url) props.onOpenUrl(props.resource.url);
      }}
    >
      {content}
    </button>
  );
}

export function InspectorResourcesPane(props: {
  workspaceRoot: string;
  resources: readonly InspectorResource[];
  description?: string;
  loading?: boolean;
  emptyLabel: string;
  testId: string;
  onOpenFile: (path: string) => void;
  onOpenUrl: (url: string) => void;
}) {
  const [searchResultsExpanded, setSearchResultsExpanded] = useState(false);
  const sourceResources = useMemo(
    () => props.resources.filter(isSourceResource),
    [props.resources],
  );
  const sourceGroups = useMemo(
    () => groupInspectorSourceResources(sourceResources),
    [sourceResources],
  );
  const isSourceList =
    props.resources.length > 0 && sourceResources.length === props.resources.length;
  const primaryResources: readonly InspectorResource[] = isSourceList
    ? sourceGroups.primary
    : props.resources;

  return (
    <div className="space-y-1.5" data-testid={props.testId}>
      {props.description ? (
        <div className="rounded-md bg-[var(--app-subtle-bg)] px-2.5 py-1.5 text-[11px] leading-4 text-[var(--app-hint)]">
          {props.description}
        </div>
      ) : null}
      {props.resources.length === 0 && !props.loading ? (
        <div className="py-1 text-sm text-[var(--app-hint)]">{props.emptyLabel}</div>
      ) : props.resources.length > 0 ? (
        <div>
          {primaryResources.map((resource) => (
            <ResourceRow
              key={resource.id}
              resource={resource}
              workspaceRoot={props.workspaceRoot}
              onOpenFile={props.onOpenFile}
              onOpenUrl={props.onOpenUrl}
            />
          ))}
          {isSourceList && sourceGroups.searchResults.length > 0 ? (
            <section className="mt-1 border-t border-[var(--app-border)] pt-1">
              <button
                type="button"
                className="flex min-h-[38px] w-full items-center gap-1.5 rounded-md px-1.5 py-1 text-left transition-colors hover:bg-[var(--app-bg)]"
                aria-expanded={searchResultsExpanded}
                onClick={() => setSearchResultsExpanded((expanded) => !expanded)}
              >
                {searchResultsExpanded ? (
                  <ChevronDown size={14} className="shrink-0 text-[var(--app-hint)]" />
                ) : (
                  <ChevronRight size={14} className="shrink-0 text-[var(--app-hint)]" />
                )}
                <Search size={15} className="shrink-0 text-[var(--app-hint)]" />
                <div className="min-w-0 flex-1">
                  <div className="text-[13px] font-medium text-[var(--app-fg)]">
                    Web search results
                  </div>
                  <div className="truncate text-[11px] text-[var(--app-hint)]">
                    Candidate links returned by searches; not necessarily opened
                  </div>
                </div>
                <span className="shrink-0 text-[11px] tabular-nums text-[var(--app-hint)]">
                  {sourceGroups.searchResults.length}
                </span>
              </button>
              {searchResultsExpanded ? (
                <div data-testid="inspector-web-search-results">
                  {sourceGroups.searchResults.map((resource) => (
                    <ResourceRow
                      key={resource.id}
                      resource={resource}
                      workspaceRoot={props.workspaceRoot}
                      nested
                      onOpenFile={props.onOpenFile}
                      onOpenUrl={props.onOpenUrl}
                    />
                  ))}
                </div>
              ) : null}
            </section>
          ) : null}
        </div>
      ) : null}
    </div>
  );
}
