import test from "node:test";
import assert from "node:assert/strict";
import { isTerminalProtocolResponse } from "./terminal-protocol-response";

test("recognizes terminal capability responses generated by xterm", () => {
  assert.equal(isTerminalProtocolResponse("\x1b[24;80R"), true);
  assert.equal(isTerminalProtocolResponse("\x1b[?1;2c"), true);
  assert.equal(isTerminalProtocolResponse("\x1b[>0;276;0c"), true);
  assert.equal(isTerminalProtocolResponse("\x1b[?0u"), true);
  assert.equal(isTerminalProtocolResponse("\x1b]10;rgb:ffff/ffff/ffff\x1b\\"), true);
  assert.equal(
    isTerminalProtocolResponse("\x1b[24;80R\x1b]11;rgb:0000/0000/0000\x1b\\"),
    true,
  );
});

test("does not treat ordinary user input as terminal protocol responses", () => {
  assert.equal(isTerminalProtocolResponse("a"), false);
  assert.equal(isTerminalProtocolResponse("\r"), false);
  assert.equal(isTerminalProtocolResponse("\x1b[A"), false);
  assert.equal(isTerminalProtocolResponse("a\x1b[24;80R"), false);
});
